"""add_security_and_performance_improvements

Revision ID: 1eb800671c27
Revises: 47d453f6823b
Create Date: 2025-11-28 12:22:52.944911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eb800671c27'
down_revision: Union[str, Sequence[str], None] = '47d453f6823b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_product_brand_price', 'products', ['brand_id', 'price'], unique=False)
    op.create_index('ix_product_category_active', 'products', ['category_id', 'is_active'], unique=False)
    op.create_index('ix_product_category_price', 'products', ['category_id', 'price'], unique=False)
    op.create_index(op.f('ix_products_is_active'), 'products', ['is_active'], unique=False)
    op.create_index(op.f('ix_products_price'), 'products', ['price'], unique=False)
    op.add_column('user', sa.Column('reset_token', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('reset_token_expiry', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_reset_token'), 'user', ['reset_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_reset_token'), table_name='user')
    op.drop_column('user', 'reset_token_expiry')
    op.drop_column('user', 'reset_token')
    op.drop_index(op.f('ix_products_price'), table_name='products')
    op.drop_index(op.f('ix_products_is_active'), table_name='products')
    op.drop_index('ix_product_category_price', table_name='products')
    op.drop_index('ix_product_category_active', table_name='products')
    op.drop_index('ix_product_brand_price', table_name='products')
    # ### end Alembic commands ###
