"""Update order schemas for admin panel

Revision ID: 3fa48eb3d8aa
Revises: b30a83cab0a7
Create Date: 2025-11-05 15:29:15.950436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fa48eb3d8aa'
down_revision: Union[str, Sequence[str], None] = 'b30a83cab0a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_media_category_id'), 'media', ['category_id'], unique=False)
    op.create_index(op.f('ix_media_product_id'), 'media', ['product_id'], unique=False)
    op.alter_column('orders', 'order_number',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=9),
               existing_nullable=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_index(op.f('ix_products_brand_id'), 'products', ['brand_id'], unique=False)
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_index(op.f('ix_products_brand_id'), table_name='products')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.alter_column('orders', 'order_number',
               existing_type=sa.String(length=9),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_index(op.f('ix_media_product_id'), table_name='media')
    op.drop_index(op.f('ix_media_category_id'), table_name='media')
    # ### end Alembic commands ###
