"""Added icon field

Revision ID: 61f61afc35e8
Revises: 6b15b570ef48
Create Date: 2025-10-29 21:42:48.349502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61f61afc35e8'
down_revision: Union[str, Sequence[str], None] = '6b15b570ef48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Сначала добавляем колонку как nullable
    op.add_column('categories', sa.Column('icon_url', sa.String(), nullable=True))
    
    # Заполняем существующие записи дефолтным значением
    op.execute("UPDATE categories SET icon_url = '' WHERE icon_url IS NULL")
    
    # Теперь делаем колонку NOT NULL
    op.alter_column('categories', 'icon_url', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'icon_url')
    # ### end Alembic commands ###
