"""add favorites and favorite_items tables

Revision ID: 89b1a44b2544
Revises: 01b62b200b4f
Create Date: 2025-11-01 18:01:15.142447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89b1a44b2544'
down_revision: Union[str, Sequence[str], None] = '01b62b200b4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_favorite_expires_at', 'favorites', ['expires_at'], unique=False)
    op.create_index('ix_favorite_session_id', 'favorites', ['session_id'], unique=False)
    op.create_index('ix_favorite_user_id', 'favorites', ['user_id'], unique=False)
    op.create_index(op.f('ix_favorites_session_id'), 'favorites', ['session_id'], unique=False)
    op.create_index(op.f('ix_favorites_user_id'), 'favorites', ['user_id'], unique=False)
    op.create_table('favorite_items',
    sa.Column('favorite_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['favorite_id'], ['favorites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('favorite_id', 'product_id', name='uq_favorite_product')
    )
    op.create_index('ix_favorite_items_favorite_id', 'favorite_items', ['favorite_id'], unique=False)
    op.create_index('ix_favorite_items_product_id', 'favorite_items', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_favorite_items_product_id', table_name='favorite_items')
    op.drop_index('ix_favorite_items_favorite_id', table_name='favorite_items')
    op.drop_table('favorite_items')
    op.drop_index(op.f('ix_favorites_user_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_session_id'), table_name='favorites')
    op.drop_index('ix_favorite_user_id', table_name='favorites')
    op.drop_index('ix_favorite_session_id', table_name='favorites')
    op.drop_index('ix_favorite_expires_at', table_name='favorites')
    op.drop_table('favorites')
    # ### end Alembic commands ###
