"""Added upds

Revision ID: 90c6dc13612c
Revises: bbf100b69d16
Create Date: 2025-10-24 17:46:52.010959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90c6dc13612c'
down_revision: Union[str, Sequence[str], None] = 'bbf100b69d16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'media', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'media', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'media', type_='foreignkey')
    op.drop_constraint(None, 'media', type_='foreignkey')
    # ### end Alembic commands ###
