"""change_media_id_to_uuid

Revision ID: b24d9a86d715
Revises: f1267494fb62
Create Date: 2025-10-24 16:17:03.674392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b24d9a86d715'
down_revision: Union[str, Sequence[str], None] = 'f1267494fb62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Сначала создаем новую колонку с UUID
    op.add_column('media', sa.Column('new_id', sa.UUID(), nullable=True))
    
    # Заполняем новую колонку UUID значениями для существующих записей
    op.execute("UPDATE media SET new_id = gen_random_uuid()")
    
    # Делаем новую колонку NOT NULL
    op.alter_column('media', 'new_id', nullable=False)
    
    # Удаляем старую колонку id
    op.drop_column('media', 'id')
    
    # Переименовываем new_id в id
    op.alter_column('media', 'new_id', new_column_name='id')
    
    # Добавляем первичный ключ
    op.create_primary_key('media_pkey', 'media', ['id'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Удаляем первичный ключ
    op.drop_constraint('media_pkey', 'media', type_='primary')
    
    # Создаем новую колонку с INTEGER
    op.add_column('media', sa.Column('new_id', sa.INTEGER(), nullable=True))
    
    # Заполняем новую колонку последовательными значениями
    op.execute("""
        UPDATE media SET new_id = row_number() OVER (ORDER BY id)
    """)
    
    # Делаем новую колонку NOT NULL
    op.alter_column('media', 'new_id', nullable=False)
    
    # Удаляем старую колонку id
    op.drop_column('media', 'id')
    
    # Переименовываем new_id в id
    op.alter_column('media', 'new_id', new_column_name='id')
    
    # Добавляем первичный ключ
    op.create_primary_key('media_pkey', 'media', ['id'])
    
    # ### end Alembic commands ###
