"""Added icon field

Revision ID: cc0a4f9f5b18
Revises: 61f61afc35e8
Create Date: 2025-10-29 21:46:17.930937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc0a4f9f5b18'
down_revision: Union[str, Sequence[str], None] = '61f61afc35e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'icon_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'icon_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
